<?php

/**
 * @file
 * Siteinfo custom
 */

/**
 * Implements hook_menu().
 */
function siteinfo_custom_menu() {
  $items = array();

  $items['admin/site-info-custom/config'] = array(
    'title' => 'Site Configuration',
    'description' => 'Site Configuration page',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('siteinfo_custom_site_setings_form'),
    'access arguments' => array('administer custom siteinfo content configuration'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function siteinfo_custom_permission() {
  $return = array();

  $return['administer custom siteinfo content configuration'] = array(
    'title' => t('Allow to administer custom site settings'),
  );

  return $return;
}

/**
 * Site configuration form.
 */
function siteinfo_custom_site_setings_form($form) {

  $form['socials'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social links'),
    '#weight' => 1,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['socials']['siteinfo_facebook'] = array(
    '#type' => 'textfield',
    '#required' => FALSE,
    '#title' => t('Facebook url'),
    '#default_value' => variable_get('siteinfo_facebook', ''),
  );
  $form['socials']['siteinfo_twitter'] = array(
    '#type' => 'textfield',
    '#required' => FALSE,
    '#title' => t('Twitter url'),
    '#default_value' => variable_get('siteinfo_twitter', ''),
  );
  $form['socials']['siteinfo_instagram'] = array(
    '#type' => 'textfield',
    '#required' => FALSE,
    '#title' => t('Instagram url'),
    '#default_value' => variable_get('siteinfo_instagram', ''),
  );

  $form['footer_data'] = array(
    '#type' => 'fieldset',
    '#title' => t('Footer site info'),
    '#weight' => 1,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['footer_data']['siteinfo_copyright'] = array(
    '#type' => 'textfield',
    '#required' => FALSE,
    '#title' => t('Copyright'),
    '#default_value' => variable_get('siteinfo_copyright', ''),
    '#description' => t('Use %year% for current year.'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_page().
 */
function siteinfo_custom_preprocess_page(&$vars) {
  $facebook_url = variable_get('siteinfo_facebook', '');
  if(!empty($facebook_url)) {
    $vars['facebook_link'] = l('', $facebook_url, array('attributes' => array('class' => array('ss-social-regular', 'ss-facebook'), 'target' => '_blank')));
  }
  $twitter_url = variable_get('siteinfo_twitter', '');
  if(!empty($twitter_url)) {
    $vars['twitter_link'] = l('', $twitter_url, array('attributes' => array('class' => array('ss-social-regular', 'ss-twitter'), 'target' => '_blank')));
  }
  $instagram_url = variable_get('siteinfo_instagram', '');
  if(!empty($instagram_url)) {
    $vars['instagram_link'] = l('', $instagram_url, array('attributes' => array('class' => array('ss-social-regular', 'ss-instagram'), 'target' => '_blank')));
  }

  $vars['copyright'] = str_replace('%year%', date("Y"), variable_get('siteinfo_copyright', ''));

}