<footer id="site-footer" class="site-footer">
  <div class="footer-top">
    <div class="site-container">
      <ul class="menu">
        <li>
          <a href="#">Parking/Transportation</a>
          <ul>
            <li><a href="#">Parking Rates & Info</a></li>
            <li><a href="#">Accessibility</a></li>
            <li><a href="#">Rental Cars</a></li>
            <li><a href="#">Public Transportation</a></li>
            <li><a href="#">Driving Directions</a></li>
            <li><a href="#">Construction Updates</a></li>
          </ul>
        </li>
        <li><a href="#">Airport Information</a></li>
        <li><a href="#">Partnering With Us</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      <div class="social">
        <ul>
          <li><a class="ss-social-regular ss-facebook" href="#"></a></li>
          <li><a class="ss-social-regular ss-twitter" href="#"></a></li>
          <li><a class="ss-social-regular ss-instagram" href="#"></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="logo"><a href="#"><img src="theme/images/logo-min-new.png" alt=""/></a></div>
    <p>©2015 Will Rogers World Airport. All Rights Reserved.</p>
  </div>
</footer>