<header id="site-header" class="site-header">
  <div class="site-container">
    <div class="logo">
      <a href="#"><img src="theme/images/logo-header-new.png" alt=""/>
      </a></div>
    <div class="search-wrapper">
      <div class="form-item form-type-textfield form-item-search-block-form">
        <label class="element-invisible" for="edit-search-block-form--2">Search </label>
        <input title="Enter the terms you wish to search for." placeholder="Find what you’re looking for" type="text"
               id="edit-search-block-form--2" name="search_block_form" value="" size="15" maxlength="128"
               class="form-text form-autocomplete ui-autocomplete-processed ui-autocomplete-input"
               data-sa-theme="minimal" autocomplete="off"><span role="status" aria-live="polite"
                                                                class="ui-helper-hidden-accessible"></span>
        <ul class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all" id="ui-id-1" tabindex="0"
            data-sa-theme="minimal"></ul>
      </div>
      <div class="form-actions form-wrapper" id="edit-actions">
        <input type="submit" id="edit-submit" name="op" value="Search" class="form-submit"></div>
      <div class="btn-search">
        <a href=""></a>
      </div>

      <!--      <ul class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all" id="ui-id-1" tabindex="0"-->
      <!--          data-sa-theme="minimal"-->
      <!--      ">-->
      <!--      <div class="show-all ui-menu-item" ui-menu-item-first="" role="presentation"><a-->
      <!--          class="btn-show-all ui-corner-all" id="ui-id-9" tabindex="-1">-->
      <!--          <div class="ui-autocomplete-fields first">-->
      <!--            <div class="ui-autocomplete-field-label">Show all results</div>-->
      <!--          </div>-->
      <!--        </a></div>-->
      <!--      <li class="ui-menu-item-first ui-menu-item ui-menu-item-even" role="presentation"><a id="ui-id-10"-->
      <!--                                                                                           class="ui-corner-all"-->
      <!--                                                                                           tabindex="-1">-->
      <!--          <div class="ui-autocomplete-fields first">-->
      <!--            <div class="ui-autocomplete-field-title">Ga<span class="ui-autocomplete-field-term">tes</span></div>-->
      <!--            <div class="ui-autocomplete-field-path pull-right"><span>Maps</span><span>Gates</span></div>-->
      <!--          </div>-->
      <!--        </a></li>-->
      <!--      <li class="ui-menu-item-first ui-menu-item ui-menu-item-odd" role="presentation"><a id="ui-id-11"-->
      <!--                                                                                          class="ui-corner-all"-->
      <!--                                                                                          tabindex="-1">-->
      <!--          <div class="ui-autocomplete-fields first">-->
      <!--            <div class="ui-autocomplete-field-title"><span class="ui-autocomplete-field-term">tes</span>t</div>-->
      <!--            <div class="ui-autocomplete-field-path pull-right"></div>-->
      <!--          </div>-->
      <!--        </a></li>-->
      <!--      <li class="ui-menu-item-first ui-menu-item ui-menu-item-even" role="presentation"><a id="ui-id-12"-->
      <!--                                                                                           class="ui-corner-all"-->
      <!--                                                                                           tabindex="-1">-->
      <!--          <div class="ui-autocomplete-fields first">-->
      <!--            <div class="ui-autocomplete-field-title"><span class="ui-autocomplete-field-term">tes</span>t2</div>-->
      <!--            <div class="ui-autocomplete-field-path pull-right"></div>-->
      <!--          </div>-->
      <!--        </a></li>-->
      <!--      </ul>-->
    </div>
    <div class="weather">
      <span class="temp">68</span>
      <span class="icon"><img src="theme/images/icons/icon-rain.png" alt=""/></span>
    </div>
<!--    <nav class="nav">-->
<!--      <div id="block-menu-block-1" class="block block-menu-block">-->
<!--        <a class="btn-nav" href="#"><span></span></a>-->
<!---->
<!--        <div class="menu-block-wrapper menu-block-1 menu-name-main-menu parent-mlid-0 menu-level-1">-->
<!--          <ul class="menu">-->
<!--            <li class="first leaf active menu-mlid-1224"><a href="/" title="" class="active">Home</a></li>-->
<!--            <li class="expanded menu-mlid-218"><a href="/content/arrivals" title="">Flights<span-->
<!--                  class="icon-next-menu"></span></a>-->
<!--              <ul class="menu">-->
<!--                <li class="back-nav-btn"><a href="#">back</a></li>-->
<!--                <li class="first leaf menu-mlid-550"><a href="/content/arrivals">Arrivals</a></li>-->
<!--                <li class="leaf menu-mlid-551"><a href="/content/departures">Departures</a></li>-->
<!--                <li class="leaf menu-mlid-1226"><a href="/content/under-construction" title="">Airport&nbsp;Delays</a>-->
<!--                </li>-->
<!--                <li class="expanded menu-mlid-606"><a href="/content/airlines-0">Airlines<span-->
<!--                      class="icon-next-menu"></span></a>-->
<!--                  <ul class="menu">-->
<!--                    <li class="back-nav-btn"><a href="#">back</a></li>-->
<!--                    <li class="first leaf menu-mlid-607"><a href="/content/airlines-0#item-0" title="">Alaska</a></li>-->
<!--                    <li class="leaf menu-mlid-608"><a href="/content/airlines-0#item-1" title="">Allegiant</a></li>-->
<!--                    <li class="leaf menu-mlid-609"><a href="/content/airlines-0#item-2" title="">American</a></li>-->
<!--                    <li class="leaf menu-mlid-610"><a href="/content/airlines-0#item-3" title="">Delta</a></li>-->
<!--                    <li class="leaf menu-mlid-611"><a href="/content/airlines-0#item-4" title="">Southwest</a></li>-->
<!--                    <li class="last leaf menu-mlid-612"><a href="/content/airlines-0#item-5" title="">United</a></li>-->
<!--                  </ul>-->
<!--                </li>-->
<!--                <li class="leaf menu-mlid-1227"><a href="/content/under-construction" title="">Air&nbsp;Traffic</a></li>-->
<!--                <li class="last leaf active menu-mlid-1228"><a href="/" title="" class="active">Nonstop&nbsp;Cities</a>-->
<!--                </li>-->
<!--              </ul>-->
<!--            </li>-->
<!--            <li class="expanded menu-mlid-647"><a href="/map" title="">Maps<span class="icon-next-menu"></span></a>-->
<!--              <ul class="menu">-->
<!--                <li class="back-nav-btn"><a href="#">back</a></li>-->
<!--                <li class="first leaf menu-mlid-1232"><a href="/map#el-level-parking" title="">Parking</a></li>-->
<!--                <li class="leaf menu-mlid-1229"><a href="/map#el-level-upper" title="">Tickets</a></li>-->
<!--                <li class="leaf menu-mlid-1233"><a href="/map#el-level-upper" title="">Gates</a></li>-->
<!--                <li class="leaf menu-mlid-1231"><a href="/map#el-level-lower" title="">Baggage</a></li>-->
<!--                <li class="leaf menu-mlid-1234"><a href="/content/pet-relief" title="">Pet&nbsp;Relief</a></li>-->
<!--                <li class="leaf menu-mlid-1235"><a href="/content/ymca-military-welcome-center" title="">Military&nbsp;Welcome&nbsp;Center</a>-->
<!--                </li>-->
<!--                <li class="last leaf menu-mlid-1230"><a href="/map#el-level-lower" title="">Rental&nbsp;Cars</a></li>-->
<!--              </ul>-->
<!--            </li>-->
<!--            <li class="expanded menu-mlid-1236"><a href="/content/accessibility" title="">Parking<span-->
<!--                  class="icon-next-menu"></span></a>-->
<!--              <ul class="menu">-->
<!--                <li class="back-nav-btn"><a href="#">back</a></li>-->
<!--                <li class="first leaf menu-mlid-1238"><a href="/content/accessibility" title="">Accessibility</a></li>-->
<!--                <li class="leaf menu-mlid-1237"><a-->
<!--                    href="/content/parking-rates">Parking&nbsp;Rates&nbsp;&amp;&nbsp;Info</a></li>-->
<!--                <li class="last leaf menu-mlid-1281"><a href="/content/rental-cars">Rental cars</a></li>-->
<!--              </ul>-->
<!--            </li>-->
<!--            <li class="leaf menu-mlid-1239"><a href="/news" title="">News</a></li>-->
<!--            <li class="last expanded menu-mlid-1240"><a href="/content/art-will" title="">Airport&nbsp;Info<span-->
<!--                  class="icon-next-menu"></span></a>-->
<!--              <ul class="menu">-->
<!--                <li class="back-nav-btn"><a href="#">back</a></li>-->
<!--                <li class="first leaf menu-mlid-1241"><a href="/content/art-will" title="">Art&nbsp;At&nbsp;Will</a>-->
<!--                </li>-->
<!--                <li class="leaf menu-mlid-1247"><a href="/content/frequently-asked-questions" title="">FAQs</a></li>-->
<!--                <li class="leaf menu-mlid-1244"><a href="/content/food-beverage">Food&nbsp;&amp;&nbsp;Beverage</a></li>-->
<!--                <li class="leaf menu-mlid-1243"><a href="/content/public-transportation">Public&nbsp;Transportation</a>-->
<!--                </li>-->
<!--                <li class="leaf menu-mlid-1248"><a href="/content/security-tsa">Security/TSA</a></li>-->
<!--                <li class="leaf menu-mlid-1242"><a href="/content/services" title="">Services</a></li>-->
<!--                <li class="leaf menu-mlid-1245"><a href="/content/shopping" title="">Shopping</a></li>-->
<!--                <li class="leaf menu-mlid-1249"><a href="/content/travel-tips">Travel&nbsp;Tips</a></li>-->
<!--                <li class="last leaf menu-mlid-1246"><a href="/content/wifi">Wifi</a></li>-->
<!--              </ul>-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </div>-->
<!--    </nav>-->

        <nav class="nav">
          <a class="btn-nav" href="#"><span></span></a>

          <div class="menu-block-wrapper">
                   <ul class="menu">
              <li class="first leaf active menu-mlid-1224"><a href="/" title="" class="active">Home</a></li>
              <li class="expanded menu-mlid-218"><a href="/content/arrivals" title="">Flights<span
                    class="icon-next-menu"></span></a>
                <ul class="menu">
                  <li class="back-nav-btn"><a href="#">back</a></li>
                  <li class="first leaf menu-mlid-550"><a href="/content/arrivals">Arrivals</a></li>
                  <li class="leaf menu-mlid-551"><a href="/content/departures">Departures</a></li>
                  <li class="leaf menu-mlid-1226"><a href="/content/under-construction" title="">Airport&nbsp;Delays</a>
                  </li>
                  <li class="expanded menu-mlid-606"><a href="/content/airlines-0">Airlines<span
                        class="icon-next-menu"></span></a>
                    <ul class="menu">
                      <li class="back-nav-btn"><a href="#">back</a></li>
                      <li class="first leaf menu-mlid-607"><a href="/content/airlines-0#item-0" title="">Alaska</a></li>
                      <li class="leaf menu-mlid-608"><a href="/content/airlines-0#item-1" title="">Allegiant</a></li>
                      <li class="leaf menu-mlid-609"><a href="/content/airlines-0#item-2" title="">American</a></li>
                      <li class="leaf menu-mlid-610"><a href="/content/airlines-0#item-3" title="">Delta</a></li>
                      <li class="leaf menu-mlid-611"><a href="/content/airlines-0#item-4" title="">Southwest</a></li>
                      <li class="last leaf menu-mlid-612"><a href="/content/airlines-0#item-5" title="">United</a></li>
                    </ul>
                  </li>
                  <li class="leaf menu-mlid-1227"><a href="/content/under-construction" title="">Air&nbsp;Traffic</a></li>
                  <li class="last leaf active menu-mlid-1228"><a href="/" title="" class="active">Nonstop&nbsp;Cities</a>
                  </li>
                </ul>
              </li>
              <li class="expanded menu-mlid-647"><a href="/map" title="">Maps<span class="icon-next-menu"></span></a>
                <ul class="menu">
                  <li class="back-nav-btn"><a href="#">back</a></li>
                  <li class="first leaf menu-mlid-1232"><a href="/map#el-level-parking" title="">Parking</a></li>
                  <li class="leaf menu-mlid-1229"><a href="/map#el-level-upper" title="">Tickets</a></li>
                  <li class="leaf menu-mlid-1233"><a href="/map#el-level-upper" title="">Gates</a></li>
                  <li class="leaf menu-mlid-1231"><a href="/map#el-level-lower" title="">Baggage</a></li>
                  <li class="leaf menu-mlid-1234"><a href="/content/pet-relief" title="">Pet&nbsp;Relief</a></li>
                  <li class="leaf menu-mlid-1235"><a href="/content/ymca-military-welcome-center" title="">Military&nbsp;Welcome&nbsp;Center</a>
                  </li>
                  <li class="last leaf menu-mlid-1230"><a href="/map#el-level-lower" title="">Rental&nbsp;Cars</a></li>
                </ul>
              </li>
              <li class="expanded menu-mlid-1236"><a href="/content/accessibility" title="">Parking<span
                    class="icon-next-menu"></span></a>
                <ul class="menu">
                  <li class="back-nav-btn"><a href="#">back</a></li>
                  <li class="first leaf menu-mlid-1238"><a href="/content/accessibility" title="">Accessibility</a></li>
                  <li class="leaf menu-mlid-1237"><a
                      href="/content/parking-rates">Parking&nbsp;Rates&nbsp;&amp;&nbsp;Info</a></li>
                  <li class="last leaf menu-mlid-1281"><a href="/content/rental-cars">Rental cars</a></li>
                </ul>
              </li>
              <li class="leaf menu-mlid-1239"><a href="/news" title="">News</a></li>
              <li class="last expanded menu-mlid-1240"><a href="/content/art-will" title="">Airport&nbsp;Info<span
                    class="icon-next-menu"></span></a>
                <ul class="menu">
                  <li class="back-nav-btn"><a href="#">back</a></li>
                  <li class="first leaf menu-mlid-1241"><a href="/content/art-will" title="">Art&nbsp;At&nbsp;Will</a>
                  </li>
                  <li class="leaf menu-mlid-1247"><a href="/content/frequently-asked-questions" title="">FAQs</a></li>
                  <li class="leaf menu-mlid-1244"><a href="/content/food-beverage">Food&nbsp;&amp;&nbsp;Beverage</a></li>
                  <li class="leaf menu-mlid-1243"><a href="/content/public-transportation">Public&nbsp;Transportation</a>
                  </li>
                  <li class="leaf menu-mlid-1248"><a href="/content/security-tsa">Security/TSA</a></li>
                  <li class="leaf menu-mlid-1242"><a href="/content/services" title="">Services</a></li>
                  <li class="leaf menu-mlid-1245"><a href="/content/shopping" title="">Shopping</a></li>
                  <li class="leaf menu-mlid-1249"><a href="/content/travel-tips">Travel&nbsp;Tips</a></li>
                  <li class="last leaf menu-mlid-1246"><a href="/content/wifi">Wifi</a></li>
                </ul>
              </li>
            </ul>

            <ul class="menu mobile-menu">
              <li>
                <a href="#">Parking/Transportation</a>
                <ul>
                  <li><a href="#">Parking Rates & Info</a></li>
                  <li><a href="#">Accessibility</a></li>
                  <li><a href="#">Rental Cars</a></li>
                  <li><a href="#">Public Transportation</a></li>
                  <li><a href="#">Driving Directions</a></li>
                  <li><a href="#">Construction Updates</a></li>
                </ul>
              </li>
              <li><a href="#">Airport Information</a></li>
              <li><a href="#">Partnering With Us</a></li>
              <li><a href="#">About Us</a></li>
              <li><a href="#">News</a></li>
              <li><a href="#">Contacts</a></li>
            </ul>
            <div class="social">
              <ul>
                <li><a class="ss-social-regular ss-facebook" href="#"></a></li>
                <li><a class="ss-social-regular ss-twitter" href="#"></a></li>
                <li><a class="ss-social-regular ss-instagram" href="#"></a></li>
              </ul>
            </div>
          </div>
        </nav>
  </div>
</header>