<?php
/**
 * @file
 *  WRWA jetset calendar
 */

define('WRWA_JETSET_STAGE1_TID', 1);
define('WRWA_JETSET_STAGE2_TID', 2);
define('WRWA_JETSET_STAGE3_TID', 3);

/**
 * Implements hook_menu().
 */
function wrwa_jetset_menu() {
  $items = array();

  $items['calendar/day/%/%ctools_js'] = array(
    'title' => 'Title',
    'description' => 'Description',
    'access callback' => TRUE,
    'page callback' => 'wrwa_jetset_load_calendar_day',
    'page arguments' => array(2, 3),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'ajax_deliver',
  );

  return $items;
}

/**
 * Page ajax callback.
 *
 * @param $date
 * @param null $js
 */
function wrwa_jetset_load_calendar_day($date, $js = NULL) {

  if($js) {

    $commands = array();

    $date_obj = date_create_from_format('Y-m-d', $date);
    if(!empty($date_obj)) {
      //if valid date
      $html = views_embed_view('calendar', 'block_3', $date);
      $commands[] = ajax_command_replace('.wrwa-jetset-views-day-wrapper', $html);
      $commands[] = array(
        'command' => 'wrwaJetsetSetDate', // Custom ajax command. @see wrwa_jetset.js
        'id'  => 'calendar-' . $date,
        'cells_selector' => '.wrwa-calendar-views-month-wrapper td',
      );
    }

    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );

  } else {
    drupal_goto();
  }
}

function wrwa_jetset_preprocess_views_view(&$vars) {

  $view = $vars['view'];

  if($view->name == 'calendar') {

    if($view->current_display == 'block_3') {
      $vars['classes_array'][] = 'wrwa-jetset-views-day-wrapper';

      drupal_add_library('system', 'drupal.ajax');
      drupal_add_js(drupal_get_path('module', 'wrwa_jetset') . '/js/wrwa_jetsets_calendar.js');

      $date_arg = $view->args[0];
      $date_arg_obj = new DateObject($date_arg);
      $now_date_obj = new DateObject();
      if($now_date_obj->format('Y-m-d') == $date_arg) {
        $vars['is_today'] = TRUE;
      }

      $vars['formatted_date'] = $date_arg_obj->format('l, F d, Y');
    } else if($view->current_display == 'block_1') {
      $vars['classes_array'][] = 'wrwa-calendar-views-month-wrapper';
    }

  }
}

/**
 * Implements template_preprocess_calendar_datebox().
 * Events Calendar
 */
function wrwa_jetset_preprocess_calendar_datebox(&$vars) {
  if(!empty($vars['view']->name)) {

    switch($vars['view']->name){
      case 'calendar':
        //dsm($vars);
        if ($vars['mini']) {
          if (!empty($vars['selected'])) {
            $link_attributes = array('class' => array('calendar-active-day', 'use-ajax'));
            $vars['link'] = l($vars['day'], 'calendar/day/' . $vars['date'] . '/nojs', array('attributes' => $link_attributes));
          }
        }
        break;
    }

  }

}